name: Tests with ThingsDB on PHP^8.2

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04
    name: "Running phpunit tests for PHP ${{ matrix.php-version }} on ThingsDB"
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.3']

    services:
      thingsdb:
        image: ghcr.io/thingsdb/node:latest
        options: >-
          --init
        ports:
          - 9200:9200

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, sockets, openssl
          ini-values: max_execution_time=0

      - name: Install dependencies
        run: composer install --no-progress

      - name: Test with phpunit
        run: vendor/bin/phpunit --bootstrap bootstrap.php --configuration phpunit.xml --testsuite "ThingsDB"
